assistive_rehab::SkeletonStd Class Reference
Basic class for skeleton standard.
#include <skeleton.h>
Public Member Functions
SkeletonStd ()
Default constructor.
bool update_planes () override
Update skeleton planes.
const std::string & getType () const
Return a reference to the type of the skeleton.
void setTag (const std::string &tag)
Set the tag of the skeleton.
const std::string & getTag () const
Return a reference to the tag of the skeleton.
bool setTransformation (const yarp::sig::Matrix &T)
Set a new transformation matrix of the skeleton.
const yarp::sig::Matrix & getTransformation () const
Retrieve the transformation matrix of the skeleton.
bool setCoronal (const yarp::sig::Vector &coronal)
Set a new coronal plane to the skeleton.
bool setSagittal (const yarp::sig::Vector &sagittal)
Set a new sagittal plane to the skeleton.
bool setTransverse (const yarp::sig::Vector &transverse)
Set a new transverse plane to the skeleton.
yarp::sig::Vector getCoronal () const
Retrieve the coronal plane of the skeleton.
yarp::sig::Vector getSagittal () const
Retrieve the sagittal plane of the skeleton.
yarp::sig::Vector getTransverse () const
Retrieve the transverse plane of the skeleton.
double getMaxPath () const
Retrieve the skeleton's maximum path.
virtual yarp::os::Property toProperty ()
Export the skeleton structure as a property.
virtual void fromProperty (const yarp::os::Property &prop)
Import the skeleton structure from its properties.
unsigned int getNumKeyPoints () const
Retrieve the number of keypoints of the skeleton.
int getNumFromKey (const std::string &tag) const
Retrieve the index of the keypoint from its tag.
const KeyPoint * operator[] (const std::string &tag) const
Keypoint access.
const KeyPoint * operator[] (const unsigned int i) const
Keypoint access.
virtual void update ()
Update skeleton.
virtual void update (const std::vector< yarp::sig::Vector > &ordered)
Update skeleton from ordered list.
virtual void update (const std::vector< std::pair< std::string, yarp::sig::Vector >> &unordered)
Update skeleton from unordered list.
virtual void update (const yarp::os::Property &prop)
Update skeleton from properties.
virtual void update_withpixels (const std::vector< std::pair< yarp::sig::Vector, yarp::sig::Vector >> &ordered)
Update skeleton from ordered list.
virtual void update_withpixels (const std::vector< std::pair< std::string, std::pair< yarp::sig::Vector, yarp::sig::Vector >>> &unordered)
Update skeleton from unordered list.
virtual std::vector< yarp::sig::Vector > get_ordered () const
Retrieve the ordered list of keypoints.
virtual std::vector< std::pair< std::string, yarp::sig::Vector > > get_unordered () const
Retrieve the unordered list of keypoints.
virtual std::vector< std::pair< yarp::sig::Vector, yarp::sig::Vector > > get_ordered_withpixels () const
Retrieve the ordered list of keypoints.
virtual std::vector< std::pair< std::string, std::pair< yarp::sig::Vector, yarp::sig::Vector > > > get_unordered_withpixels () const
Retrieve the unordered list of keypoints.
void normalize (const double n=1.0)
Normalize skeleton in order to have unitary/desired distance among keypoints.
void scale (const double s)
Rescale skeleton.
void print (std::ostream &os=std::cout) const
Print skeleton information.
Protected Member Functions
yarp::os::Property helper_toproperty (KeyPoint *k) const
void helper_fromproperty (yarp::os::Bottle *prop, KeyPoint *parent)
void helper_updatefromproperty (yarp::os::Bottle *prop)
void helper_normalize (KeyPoint *k, const std::vector< yarp::sig::Vector > &helperpoints, const double n)
void helper_scale (KeyPoint *k, const std::vector< yarp::sig::Vector > &helperpoints, const double s)
double helper_getmaxpath (KeyPoint *k, std::vector< bool > &visited) const
Protected Attributes
std::string type
skeleton's type (`assistive_rehab::SkeletonStd`)
std::string tag
skeleton's tag
std::vector< KeyPoint * > keypoints
vector of pointer to KeyPoint
std::unordered_map< std::string, KeyPoint * > tag2key
map associating a tag to a pointer to a KeyPoint
std::unordered_map< KeyPoint *, unsigned int > key2id
map associating a pointer to a KeyPoint to an index
yarp::sig::Matrix T
transformation matrix
yarp::sig::Vector coronal
vector containing the normal to the coronal plane
yarp::sig::Vector sagittal
vector containing the normal to the sagittal plane
yarp::sig::Vector transverse
vector containing the normal to the transverse plane
Detailed Description
Basic class for skeleton standard.
Definition at line 528 of file skeleton.h.
Member Function Documentation
fromProperty()
void Skeleton::fromProperty (const yarp::os::Property & prop) [virtual], [inherited]
Import the skeleton structure from its properties.
Parameters
prop Property object containing the properties of a skeleton.
Available properties are:
type: string containing skeleton's type (`assistive_rehab::SkeletonStd`).
tag: string containing skeleton's tag.
transformation: 4 x 4 skeleton's roto-translation matrix.
coronal: vector containing skeleton's coronal plane.
sagittal: vector containing skeleton's sagittal plane.
transverse: vector containing skeleton's transverse plane.
skeleton: list containing keypoints with the following subproperties:
tag: string containing keypoint's tag.
status: string containing keypoint's status (updated or stale).
position: vector containing keypoint's camera coordinates x,y,z.
pixel: vector containing keypoint's image coordinates u,v.
child: list containing keypoint's child, specified as position, status, tag.
Definition at line 400 of file skeleton.cpp.
{
    for (auto &k:keypoints)
        delete k;
    keypoints.clear();
    tag2key.clear();
    key2id.clear();
    tag=prop.check("tag",Value("")).asString();
    if (prop.check("transformation"))
    {
        if (Bottle *b=prop.find("transformation").asList())
            b->write(T);
    }
    else
        T=eye(4,4);
    coronal=sagittal=transverse=zeros(3);
    if (prop.check("coronal"))
        if (Bottle *b=prop.find("coronal").asList())
            b->write(coronal);
    if (prop.check("sagittal"))
        if (Bottle *b=prop.find("sagittal").asList())
            b->write(sagittal);
    if (prop.check("transverse"))
        if (Bottle *b=prop.find("transverse").asList())
            b->write(transverse);
    helper_fromproperty(prop.find("skeleton").asList(),nullptr);
}
References assistive_rehab::Skeleton::coronal, assistive_rehab::Skeleton::key2id, assistive_rehab::Skeleton::keypoints, assistive_rehab::Skeleton::sagittal, assistive_rehab::Skeleton::T, assistive_rehab::Skeleton::tag, assistive_rehab::Skeleton::tag2key, and assistive_rehab::Skeleton::transverse.
get_ordered()
vector< Vector > Skeleton::get_ordered () const [virtual], [inherited]
Retrieve the ordered list of keypoints.
Returns
vector containing the ordered list of keypoints, each specified as vector containing the x,y,z camera coordinates.
Definition at line 581 of file skeleton.cpp.
{
    vector<Vector> ordered;
    for (auto &k:keypoints)
        ordered.push_back(k->getPoint());
    return ordered;
}
References assistive_rehab::KeyPoint::getPoint(), and assistive_rehab::Skeleton::keypoints.
get_ordered_withpixels()
vector< pair< Vector, Vector > > Skeleton::get_ordered_withpixels () const [virtual], [inherited]
Retrieve the ordered list of keypoints.
Returns
vector containing the ordered list of keypoints, each specified as a pair of vectors with x,y,z and u,v coordinates.
Definition at line 597 of file skeleton.cpp.
{
    vector<pair<Vector,Vector>> ordered;
    for (auto &k:keypoints)
        ordered.push_back(make_pair(k->getPoint(),k->getPixel()));
    return ordered;
}
References assistive_rehab::KeyPoint::getPixel(), assistive_rehab::KeyPoint::getPoint(), and assistive_rehab::Skeleton::keypoints.
get_unordered()
vector< pair< string, Vector > > Skeleton::get_unordered () const [virtual], [inherited]
Retrieve the unordered list of keypoints.
Returns
vector containing an unordered list of keypoints, each specified as pair which associates a string, containing the keypoint's tag, and a vector, containing the x,y,z camera coordinates.
Definition at line 589 of file skeleton.cpp.
{
    vector<pair<string,Vector>> unordered;
    for (auto &it:tag2key)
        unordered.push_back(make_pair(it.first,it.second->getPoint()));
    return unordered;
}
References assistive_rehab::Skeleton::tag2key.
get_unordered_withpixels()
vector< pair< string, pair< Vector, Vector > > > Skeleton::get_unordered_withpixels () const [virtual], [inherited]
Retrieve the unordered list of keypoints.
Returns
vector containing an unordered list of keypoints, each specified as pair that associates a string containing the keypoint's tag to a pair of vectors of x,y,z and u,v coordinates.
Definition at line 605 of file skeleton.cpp.
{
    vector<pair<string,pair<Vector,Vector>>> unordered;
    for (auto &it:tag2key)
        unordered.push_back(make_pair(it.first,make_pair(it.second->getPoint(),it.second->getPixel())));
    return unordered;
}
References assistive_rehab::Skeleton::tag2key.
getCoronal()
Vector Skeleton::getCoronal () const [inherited]
Retrieve the coronal plane of the skeleton.
Returns
vector containing x,y,z coordinates of the normal to skeleton's coronal plane.
Definition at line 340 of file skeleton.cpp.
{
    return coronal;
}
References assistive_rehab::Skeleton::coronal.
getMaxPath()
double Skeleton::getMaxPath () const [inherited]
Retrieve the skeleton's maximum path.
Returns
skeleton's maximum path.
Definition at line 355 of file skeleton.cpp.
{
    Vector paths(1,0.0);
    for (auto &k:keypoints)
    {
        vector<bool> visited(getNumKeyPoints(),false);
        paths.push_back(helper_getmaxpath(k,visited));
    }
    return findMax(paths);
}
References assistive_rehab::Skeleton::getNumKeyPoints(), and assistive_rehab::Skeleton::keypoints.
getNumFromKey()
int Skeleton::getNumFromKey (const std::string & tag) const [inherited]
Retrieve the index of the keypoint from its tag.
Parameters
tag string containing the keypoint's tag.
Returns
skeleton's number of keypoints.
Definition at line 431 of file skeleton.cpp.
{
    auto it1=tag2key.find(tag);
    if (it1!=tag2key.end())
    {
        auto it2=key2id.find(it1->second);
        if (it2!=key2id.end())
            return (int)it2->second;
    }
    return -1;
}
References assistive_rehab::Skeleton::key2id, assistive_rehab::Skeleton::tag, and assistive_rehab::Skeleton::tag2key.
getNumKeyPoints()
unsigned int assistive_rehab::Skeleton::getNumKeyPoints () const [inline], [inherited]
Retrieve the number of keypoints of the skeleton.
Returns
skeleton's number of keypoints.
Definition at line 383 of file skeleton.h.
{ return (unsigned int)keypoints.size(); }
References assistive_rehab::Skeleton::keypoints.
Referenced by assistive_rehab::Skeleton::getMaxPath().
getSagittal()
Vector Skeleton::getSagittal () const [inherited]
Retrieve the sagittal plane of the skeleton.
Returns
vector containing the x,y,z coordinates of the normal skeleton's sagittal plane.
Definition at line 345 of file skeleton.cpp.
{
    return sagittal;
}
References assistive_rehab::Skeleton::sagittal.
getTag()
const std::string& assistive_rehab::Skeleton::getTag () const [inline], [inherited]
Return a reference to the tag of the skeleton.
Returns
reference to a string containing the skeleton's tag.
Definition at line 278 of file skeleton.h.
{ return tag; }
References assistive_rehab::Skeleton::tag.
getTransformation()
const yarp::sig::Matrix& assistive_rehab::Skeleton::getTransformation () const [inline], [inherited]
Retrieve the transformation matrix of the skeleton.
Returns
reference to the skeleton's transformation matrix.
Note
if the transformation matrix is the identity matrix, keypoints are defined with respect to the camera.
Definition at line 291 of file skeleton.h.
{ return T; }
References assistive_rehab::Skeleton::T.
getTransverse()
Vector Skeleton::getTransverse () const [inherited]
Retrieve the transverse plane of the skeleton.
Returns
vector containing the x,y,z coordinates of the normal skeleton's sagittal plane.
Definition at line 350 of file skeleton.cpp.
{
    return transverse;
}
References assistive_rehab::Skeleton::transverse.
getType()
const std::string& assistive_rehab::Skeleton::getType () const [inline], [inherited]
Return a reference to the type of the skeleton.
Returns
reference to the skeleton's type.
Definition at line 266 of file skeleton.h.
{ return type; }
References assistive_rehab::Skeleton::type.
normalize()
void Skeleton::normalize (const double n = 1.0) [inherited]
Normalize skeleton in order to have unitary/desired distance among keypoints.
Parameters
n double containing the normalization factor.
Definition at line 613 of file skeleton.cpp.
{
    if (keypoints.size()>0)
    {
        vector<Vector> helperpoints;
        for (auto &k:keypoints)
            helperpoints.push_back(k->getPoint());
        helper_normalize(keypoints[0],helperpoints,n);
    }
}
References assistive_rehab::KeyPoint::getPoint(), and assistive_rehab::Skeleton::keypoints.
operator[]() [1/2]
const KeyPoint* assistive_rehab::Skeleton::operator[] (const std::string & tag) const [inherited]
Keypoint access.
Returns a pointer to the keypoint specified by its tag.
Parameters
tag string containing the keypoint's tag.
Returns
a (const) pointer to the keypoint.
operator[]() [2/2]
const KeyPoint * Skeleton::operator[] (const unsigned int i) const [inherited]
Keypoint access.
Returns a pointer to the keypoint specified by its index.
Parameters
i int containing the keypoint's index.
Returns
a (const) pointer to the keypoint.
Definition at line 449 of file skeleton.cpp.
{
    return (i<keypoints.size())?keypoints[i]:nullptr;
}
References assistive_rehab::Skeleton::keypoints.
scale()
void Skeleton::scale (const double s) [inherited]
Rescale skeleton.
Parameters
s double containing the scaling factor.
Definition at line 624 of file skeleton.cpp.
{
    if (keypoints.size()>0)
    {
        vector<Vector> helperpoints;
        for (auto &k:keypoints)
            helperpoints.push_back(k->getPoint());
        helper_scale(keypoints[0],helperpoints,s);
    }
}
References assistive_rehab::KeyPoint::getPoint(), and assistive_rehab::Skeleton::keypoints.
setCoronal()
bool Skeleton::setCoronal (const yarp::sig::Vector & coronal) [inherited]
Set a new coronal plane to the skeleton.
Parameters
coronal vector containing the x,y,z coordinates of the normal to the desired plane.
Definition at line 307 of file skeleton.cpp.
{
    if (coronal.length()>=3)
    {
        this->coronal=coronal.subVector(0,2);
        return true;
    }
    else
        return false;
}
References assistive_rehab::Skeleton::coronal.
setSagittal()
bool Skeleton::setSagittal (const yarp::sig::Vector & sagittal) [inherited]
Set a new sagittal plane to the skeleton.
Parameters
sagittal vector containing the x,y,z coordinates of the normal to the desired plane.
Definition at line 318 of file skeleton.cpp.
{
    if (sagittal.length()>=3)
    {
        this->sagittal=sagittal.subVector(0,2);
        return true;
    }
    else
        return false;
}
References assistive_rehab::Skeleton::sagittal.
setTag()
void assistive_rehab::Skeleton::setTag (const std::string & tag) [inline], [inherited]
Set the tag of the skeleton.
Parameters
tag string containing the desired tag.
Definition at line 272 of file skeleton.h.
{ this->tag=tag; }
References assistive_rehab::Skeleton::tag.
setTransformation()
bool Skeleton::setTransformation (const yarp::sig::Matrix & T) [inherited]
Set a new transformation matrix of the skeleton.
Parameters
T matrix containing the desired transformation.
Definition at line 296 of file skeleton.cpp.
{
    if ((T.rows()>=4) || (T.cols()>=4))
    {
        this->T=T.submatrix(0,3,0,3);
        return true;
    }
    else
        return false;
}
References assistive_rehab::Skeleton::T.
setTransverse()
bool Skeleton::setTransverse (const yarp::sig::Vector & transverse) [inherited]
Set a new transverse plane to the skeleton.
Parameters
transverse vector containing the x,y,z coordinates of the normal to the desired plane.
Definition at line 329 of file skeleton.cpp.
{
    if (transverse.length()>=3)
    {
        this->transverse=transverse.subVector(0,2);
        return true;
    }
    else
        return false;
}
References assistive_rehab::Skeleton::transverse.
toProperty()
Property Skeleton::toProperty () [virtual], [inherited]
Export the skeleton structure as a property.
Returns
a Property object containing the properties of a skeleton.
Available properties are:
type: string containing skeleton's type (`assistive_rehab::SkeletonStd`).
tag: string containing skeleton's tag.
transformation: 4 x 4 skeleton's roto-translation matrix.
coronal: vector containing skeleton's coronal plane.
sagittal: vector containing skeleton's sagittal plane.
transverse: vector containing skeleton's transverse plane.
skeleton: list containing keypoints with the following subproperties:
tag: string containing keypoint's tag.
status: string containing keypoint's status (updated or stale).
position: vector containing keypoint's camera coordinates x,y,z.
pixel: vector containing keypoint's image coordinates u,v.
child: list containing keypoint's child, specified as position, status, tag.
Definition at line 366 of file skeleton.cpp.
{
    Property prop;
    prop.put("type",type);
    prop.put("tag",tag);
    Bottle transformation;
    transformation.addList().read(T);
    prop.put("transformation",transformation.get(0));
    Bottle plane;
    plane.addList().read(coronal);
    prop.put("coronal",plane.get(0));
    plane.clear();
    plane.addList().read(sagittal);
    prop.put("sagittal",plane.get(0));
    plane.clear();
    plane.addList().read(transverse);
    prop.put("transverse",plane.get(0));
    Bottle skeleton;
    Bottle &skeleton_=skeleton.addList();
    if (keypoints.size()>0)
    {
        Property p=helper_toproperty(keypoints[0]);
        skeleton_.addList().read(p);
    }
    prop.put("skeleton",skeleton.get(0));
    return prop;
}
References assistive_rehab::Skeleton::coronal, assistive_rehab::Skeleton::keypoints, assistive_rehab::Skeleton::sagittal, assistive_rehab::Skeleton::T, assistive_rehab::Skeleton::tag, assistive_rehab::Skeleton::transverse, and assistive_rehab::Skeleton::type.
update() [1/3]
virtual void assistive_rehab::Skeleton::update (const std::vector< std::pair< std::string, yarp::sig::Vector >> & unordered) [virtual], [inherited]
Update skeleton from unordered list.
Parameters
unordered vector containing an unordered list of keypoints. The single keypoint is specified as pair which associates a string, containing the keypoint's tag, and a vector, containing the x,y,z coordinates.
update() [2/3]
virtual void assistive_rehab::Skeleton::update (const std::vector< yarp::sig::Vector > & ordered) [virtual], [inherited]
Update skeleton from ordered list.
Parameters
ordered vector containing the ordered list of keypoints. The single keypoint is specified as vector containing the x,y,z coordinates.
update() [3/3]
virtual void assistive_rehab::Skeleton::update (const yarp::os::Property & prop) [virtual], [inherited]
Update skeleton from properties.
Parameters
prop a Property object containing skeleton information.
Available properties are:
type: string containing skeleton's type (`assistive_rehab::SkeletonStd`).
tag: string containing skeleton's tag.
transformation: 4 x 4 skeleton's roto-translation matrix.
coronal: vector containing skeleton's coronal plane.
sagittal: vector containing skeleton's sagittal plane.
transverse: vector containing skeleton's transverse plane.
skeleton: list containing keypoints with the following subproperties:
tag: string containing keypoint's tag.
status: string containing keypoint's status (updated or stale).
position: vector containing keypoint's camera coordinates x,y,z.
pixel: vector containing keypoint's image coordinates u,v.
child: list containing keypoint's child, specified as position, status, tag.
update_planes()
bool SkeletonStd::update_planes () [override], [virtual]
Update skeleton planes.
Returns
true/false on success/failure (failure occurs if not all planes are updated).
Implements assistive_rehab::Skeleton.
Definition at line 767 of file skeleton.cpp.
{
    int cnt=0;
    if (tag2key[KeyPointTag::shoulder_left]->isUpdated() &&
        tag2key[KeyPointTag::shoulder_right]->isUpdated())
    {
        sagittal=tag2key[KeyPointTag::shoulder_left]->getPoint()-
                 tag2key[KeyPointTag::shoulder_right]->getPoint();
        double n=norm(sagittal);
        if (n>0.0)
            sagittal/=n;
        cnt++;
    }
    if (tag2key[KeyPointTag::shoulder_center]->isUpdated() &&
        tag2key[KeyPointTag::hip_center]->isUpdated())
    {
        transverse=tag2key[KeyPointTag::shoulder_center]->getPoint()-
                   tag2key[KeyPointTag::hip_center]->getPoint();
        double n=norm(transverse);
        if (n>0.0)
            transverse/=n;
        cnt++;
    }
    coronal=cross(sagittal,transverse);
    return (cnt>=2);
}
References assistive_rehab::Skeleton::coronal, assistive_rehab::Skeleton::sagittal, assistive_rehab::Skeleton::tag2key, and assistive_rehab::Skeleton::transverse.
update_withpixels() [1/2]
virtual void assistive_rehab::Skeleton::update_withpixels (const std::vector< std::pair< std::string, std::pair< yarp::sig::Vector, yarp::sig::Vector >>> & unordered) [virtual], [inherited]
Update skeleton from unordered list.
Parameters
unordered vector containing an unordered list of keypoints. The single keypoint is specified as pair that associates a string containing the keypoint's tag to a pair of vectors contianing x,y,z and u,v coordinates.
update_withpixels() [2/2]
virtual void assistive_rehab::Skeleton::update_withpixels (const std::vector< std::pair< yarp::sig::Vector, yarp::sig::Vector >> & ordered) [virtual], [inherited]
Update skeleton from ordered list.
Parameters
ordered vector containing the ordered list of keypoints. The single keypoint is specified as a pair of a vector containing the x,y,z camera coordinates and a vector containing the u,v image coordinates.
The documentation for this class was generated from the following files:
/home/runner/work/assistive-rehab/assistive-rehab/gh-pages/lib/include/AssistiveRehab/skeleton.h
/home/runner/work/assistive-rehab/assistive-rehab/gh-pages/lib/src/skeleton.cpp