assistive_rehab::Dtw Class Reference
Class for DTW (Dynamic Time Warping).
#include <dtw.h>
Public Member Functions
Dtw ()
Default constructor.
Dtw (const int &win_)
Overloaded constructor.
void align (const std::vector< double > &s, const std::vector< double > &t, std::vector< double > &ws, std::vector< double > &wt)
Align two 1D temporal sequences s,t.
void align (const std::vector< std::vector< double >> &s, const std::vector< std::vector< double >> &t, std::vector< std::vector< double > > &ws, std::vector< std::vector< double > > &wt)
Align two ND temporal sequences s,t.
double getDistance () const
Retrieve the optimal distance.
virtual ~Dtw ()
Virtual destructor.
Protected Member Functions
yarp::sig::Matrix initialize (const int ns, const int nt) const
Set the elements of the distance matrix to -1, except the (0,0) element set at 0.
void getWarpingPath (const yarp::sig::Matrix &distMat, std::vector< int > &ws, std::vector< int > &wt) const
Retrieve the optimal warping path.
double computeDistance (const std::vector< double > &s, const std::vector< double > &t, yarp::sig::Matrix &distMat) const
Compute the DTW distance.
Protected Attributes
int win
window length where the warping path is searched
double d
dtw distance
Detailed Description
Class for DTW (Dynamic Time Warping).
Definition at line 75 of file dtw.h.
Constructor & Destructor Documentation
Dtw()
Dtw::Dtw (const int & win_)
Overloaded constructor.
Parameters
win_ window length where we look for the warping path. If win_ = -1, the search is carried out on the whole distance matrix.
Definition at line 26 of file dtw.cpp.
References win.
                         : Dtw()
{
    win = win_;
}
Member Function Documentation
align() [1/2]
void assistive_rehab::Dtw::align (const std::vector< double > & s, const std::vector< double > & t, std::vector< double > & ws, std::vector< double > & wt)
Align two 1D temporal sequences s,t.
Parameters
s vector containing the input signal s.
t vector containing the input signal t.
ws vector containing the aligned output s.
wt vector containing the aligned output t.
Referenced by getWarpingPath().
align() [2/2]
void assistive_rehab::Dtw::align (const std::vector< std::vector< double >> & s, const std::vector< std::vector< double >> & t, std::vector< std::vector< double > > & ws, std::vector< std::vector< double > > & wt)
Align two ND temporal sequences s,t.
Parameters
s vector of vectors containing the N components over time of the input signal s.
t vector of vectors containing the N components over time of the input signal t.
ws vector of vectors containing the N components over time of the aligned output s.
wt vector of vectors containing the N components over time of the aligned output t.
computeDistance()
double Dtw::computeDistance (const std::vector< double > & s, const std::vector< double > & t, yarp::sig::Matrix & distMat) const [protected]
Compute the DTW distance.
Parameters
s vector containing input signal s.
t vector containing input signal t.
distMat matrix containing the output distance matrix.
Returns
DTW distance.
Definition at line 47 of file dtw.cpp.
References win.
Referenced by getWarpingPath().
{
    //compute distance matrix
    int ns=(int)s.size();
    int nt=(int)t.size();
    int j1,j2;
    double cost,temp;
    for(int i=1;i<=ns;i++)
    {
        if(win==-1)
        {
            j1=1;
            j2=nt;
        }
        else
        {
            j1= i-win>1 ? i-win : 1;
            j2= i+win<nt ? i+win : nt;
        }
        for(int j=j1;j<=j2;j++)
        {
            cost=sqrt((s[i-1]-t[j-1])*(s[i-1]-t[j-1]));
            temp=distMat[i-1][j];
            if(distMat[i][j-1]!=-1)
            {
                if(temp==-1 || distMat[i][j-1]<temp)
                    temp=distMat[i][j-1];
            }
            if(distMat[i-1][j-1]!=-1)
            {
                if(temp==-1 || distMat[i-1][j-1]<temp)
                    temp=distMat[i-1][j-1];
            }
            distMat[i][j]=cost+temp;
        }
    }
    return(distMat[ns][nt]/nt);
}
getDistance()
double assistive_rehab::Dtw::getDistance () const [inline]
Retrieve the optimal distance.
Returns
optimal distance.
Definition at line 145 of file dtw.h.
References d.
{ return d; }
getWarpingPath()
void Dtw::getWarpingPath (const yarp::sig::Matrix & distMat, std::vector< int > & ws, std::vector< int > & wt) const [protected]
Retrieve the optimal warping path.
Parameters
distMat distance matrix.
ws vector containing the output warping path of s.
wt vector containing the output warping path of t.
Definition at line 87 of file dtw.cpp.
References align(), computeDistance(), d, and initialize().
{
    int m=(int)distMat.rows()-1;
    int n=(int)distMat.cols()-1;
    double temp;
    ws.push_back(m);
    wt.push_back(n);
    while((n+m) != 2)
    {
        if((n-1)==0)
        {
            m=m-1;
        }
        else if ((m-1)==0)
        {
            n=n-1;
        }
        else
        {
            temp=distMat[m-1][n];
            int c=0;
            if(distMat[m][n-1]<temp)
            {
                temp=distMat[m][n-1];
                c=1;
            }
            if(distMat[m-1][n-1]<temp)
            {
                temp=distMat[m-1][n-1];
                c=2;
            }
            switch (c)
            {
            case 0:
                m=m-1;
                break;
            case 1:
                n=n-1;
                break;
            case 2:
                m=m-1;
                n=n-1;
                break;
            }
        }
        ws.push_back(m);
        wt.push_back(n);
    }
}
initialize()
Matrix Dtw::initialize (const int ns, const int nt) const [protected]
Set the elements of the distance matrix to -1, except the (0,0) element set at 0.
Parameters
ns length of input vector s.
nt length of input vector t.
Returns
a ns x nt distance matrix.
Definition at line 31 of file dtw.cpp.
Referenced by getWarpingPath().
{
    Matrix distMat(ns+1,nt+1);
    //initialize distance matrix
    for(int i=0;i<ns+1;i++)
    {
        for(int j=0;j<nt+1;j++)
        {
            distMat[i][j]=-1;
        }
    }
    distMat[0][0]=0;
    return distMat;
}
The documentation for this class was generated from the following files:
/home/runner/work/assistive-rehab/assistive-rehab/gh-pages/lib/include/AssistiveRehab/dtw.h
/home/runner/work/assistive-rehab/assistive-rehab/gh-pages/lib/src/dtw.cpp