assistive_rehab::KeyPoint Class Reference
Basic class for single keypoint of a skeleton.
#include <skeleton.h>
Public Member Functions
KeyPoint ()
Default constructor.
KeyPoint (const std::string &tag_, const yarp::sig::Vector &point_=yarp::sig::Vector(3, std::numeric_limits< double >::quiet_NaN()), const yarp::sig::Vector &pixel_=yarp::sig::Vector(2, std::numeric_limits< double >::quiet_NaN()), const bool updated_=false)
Overloaded constructor.
KeyPoint (const KeyPoint &)=delete
Deleted copy constructor.
KeyPoint & operator= (const KeyPoint &)=delete
Deleted copy operator.
virtual ~KeyPoint ()
Virtual destructor.
bool isUpdated () const
Return true if the keypoint has been updated.
const std::string & getTag () const
Return a reference to the tag of the keypoint.
const yarp::sig::Vector & getPoint () const
Return a reference to the vector containing the keypoint's x,y,z camera coordinates.
bool setPoint (const yarp::sig::Vector &point)
Set keypoint's x,y,z camera coordinates to a desired value.
bool setPoint (const yarp::sig::Vector &point, const yarp::sig::Vector &pixel)
Set keypoint's x,y,z camera coordinates as well as u,v, image coordinates to a desired value.
const yarp::sig::Vector & getPixel () const
Return a reference to the vector containing the keypoint's u,v image coordinates.
unsigned int getNumParent () const
Retrieve the number of parents of the keypoint.
const KeyPoint * getParent (const unsigned int i) const
Get a pointer to the parent of the keypoint specified by index.
unsigned int getNumChild () const
Retrieve the number of children of the keypoint.
const KeyPoint * getChild (const unsigned int i) const
Get a pointer to the child of the keypoint specified by index.
Friends
class Skeleton
class SkeletonStd
Detailed Description
Basic class for single keypoint of a skeleton.
Definition at line 96 of file skeleton.h.
Constructor & Destructor Documentation
KeyPoint()
assistive_rehab::KeyPoint::KeyPoint (const std::string & tag_, const yarp::sig::Vector & point_ = yarp::sig::Vector(3, std::numeric_limits< double >::quiet_NaN()), const yarp::sig::Vector & pixel_ = yarp::sig::Vector(2, std::numeric_limits< double >::quiet_NaN()), const bool updated_ = false)
Overloaded constructor.
Parameters
tag_ string containing the keypoint's tag.
point_ vector containing the keypoint camera coordinates x,y,z.
pixel_ vector containing the keypoint image coordinates u,v.
updated_ true if the keypoint has been updated.
Member Function Documentation
getChild()
const KeyPoint * KeyPoint::getChild (const unsigned int i) const
Get a pointer to the child of the keypoint specified by index.
Parameters
i int containing the index of the desired keypoint.
Returns
pointer to the keypoint's child.
Definition at line 101 of file skeleton.cpp.
{
    return ((i>=0) && (i<child.size()))?child[i]:nullptr;
}
getNumChild()
unsigned int assistive_rehab::KeyPoint::getNumChild () const [inline]
Retrieve the number of children of the keypoint.
Returns
number of children of the keypoint.
Definition at line 205 of file skeleton.h.
{ return (unsigned int)child.size(); }
getNumParent()
unsigned int assistive_rehab::KeyPoint::getNumParent () const [inline]
Retrieve the number of parents of the keypoint.
Returns
number of parents of the keypoint.
Definition at line 192 of file skeleton.h.
{ return (unsigned int)parent.size(); }
getParent()
const KeyPoint * KeyPoint::getParent (const unsigned int i) const
Get a pointer to the parent of the keypoint specified by index.
Parameters
i int containing the index of the desired keypoint.
Returns
pointer to the keypoint's parent.
Definition at line 96 of file skeleton.cpp.
{
    return ((i>=0) && (i<parent.size()))?parent[i]:nullptr;
}
getPixel()
const yarp::sig::Vector& assistive_rehab::KeyPoint::getPixel () const [inline]
Return a reference to the vector containing the keypoint's u,v image coordinates.
Returns
reference to the vector containing the keypoint's u,v image coordinates.
Definition at line 186 of file skeleton.h.
Referenced by assistive_rehab::Skeleton::get_ordered_withpixels(), assistive_rehab::Skeleton::print(), and assistive_rehab::Skeleton::update().
{ return pixel; }
getPoint()
const yarp::sig::Vector& assistive_rehab::KeyPoint::getPoint () const [inline]
Return a reference to the vector containing the keypoint's x,y,z camera coordinates.
Returns
reference to the vector containing the keypoint's x,y,z camera coordinates.
Definition at line 161 of file skeleton.h.
Referenced by assistive_rehab::Skeleton::get_ordered(), assistive_rehab::Skeleton::get_ordered_withpixels(), assistive_rehab::Skeleton::normalize(), assistive_rehab::Skeleton::print(), assistive_rehab::Skeleton::scale(), assistive_rehab::Skeleton::update(), and assistive_rehab::Skeleton::~Skeleton().
{ return point; }
getTag()
const std::string& assistive_rehab::KeyPoint::getTag () const [inline]
Return a reference to the tag of the keypoint.
Returns
string containing the keypoint's tag.
Definition at line 153 of file skeleton.h.
Referenced by assistive_rehab::Skeleton::print(), and assistive_rehab::Skeleton::~Skeleton().
{ return tag; }
isUpdated()
bool assistive_rehab::KeyPoint::isUpdated () const [inline]
Return true if the keypoint has been updated.
Returns
true if the keypoint has been updated.
Definition at line 147 of file skeleton.h.
Referenced by assistive_rehab::Skeleton::print(), assistive_rehab::Skeleton::update(), assistive_rehab::SkeletonStd::update_planes(), and assistive_rehab::Skeleton::~Skeleton().
{ return updated; }
setPoint() [1/2]
bool assistive_rehab::KeyPoint::setPoint (const yarp::sig::Vector & point)
Set keypoint's x,y,z camera coordinates to a desired value.
Parameters
point vector containing the desider point.
Returns
true/false on success/failure.
Referenced by KeyPoint(), and assistive_rehab::Skeleton::update().
setPoint() [2/2]
bool assistive_rehab::KeyPoint::setPoint (const yarp::sig::Vector & point, const yarp::sig::Vector & pixel)
Set keypoint's x,y,z camera coordinates as well as u,v, image coordinates to a desired value.
Parameters
point vector containing the desider point.
pixel vector containing the desider pixel.
Returns
true/false on success/failure.
The documentation for this class was generated from the following files:
/home/runner/work/assistive-rehab/assistive-rehab/gh-pages/lib/include/AssistiveRehab/skeleton.h
/home/runner/work/assistive-rehab/assistive-rehab/gh-pages/lib/src/skeleton.cpp