/*
 * Copyright (C) 2006-2019 Istituto Italiano di Tecnologia (IIT)
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms of the
 * BSD-3-Clause license. See the accompanying LICENSE file for details.
 */

// Autogenerated by Thrift Compiler (0.12.0-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_STRUCT_FOLLOWEDSKELETONINFO_H
#define YARP_THRIFT_GENERATOR_STRUCT_FOLLOWEDSKELETONINFO_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <yarp/sig/Vector.h>

class FollowedSkeletonInfo :
        public yarp::os::idl::WirePortable
{
public:
    // Fields
    /**
     * the tag of the followed skeleton; empty otherwise.
     */
    std::string tag;
    /**
     * the x-coordinate.
     */
    double x;
    /**
     * the y-coordinate.
     */
    double y;
    /**
     * the z-coordinate.
     */
    double z;
    /**
     * the coronal plane.
     */
    yarp::sig::Vector coronal;
    /**
     * the sagittal plane.
     */
    yarp::sig::Vector sagittal;

    // Default constructor
    FollowedSkeletonInfo();

    // Constructor with field values
    FollowedSkeletonInfo(const std::string& tag,
                         const double x,
                         const double y,
                         const double z,
                         const yarp::sig::Vector& coronal,
                         const yarp::sig::Vector& sagittal);

    // Read structure on a Wire
    bool read(yarp::os::idl::WireReader& reader) override;

    // Read structure on a Connection
    bool read(yarp::os::ConnectionReader& connection) override;

    // Write structure on a Wire
    bool write(const yarp::os::idl::WireWriter& writer) const override;

    // Write structure on a Connection
    bool write(yarp::os::ConnectionWriter& connection) const override;

    // Convert to a printable string
    std::string toString() const;

    // If you want to serialize this class without nesting, use this helper
    typedef yarp::os::idl::Unwrapped<FollowedSkeletonInfo> unwrapped;

    class Editor :
            public yarp::os::Wire,
            public yarp::os::PortWriter
    {
    public:
        // Editor: default constructor
        Editor();

        // Editor: constructor with base class
        Editor(FollowedSkeletonInfo& obj);

        // Editor: destructor
        ~Editor() override;

        // Editor: Deleted constructors and operator=
        Editor(const Editor& rhs) = delete;
        Editor(Editor&& rhs) = delete;
        Editor& operator=(const Editor& rhs) = delete;
        Editor& operator=(Editor&& rhs) = delete;

        // Editor: edit
        bool edit(FollowedSkeletonInfo& obj, bool dirty = true);

        // Editor: validity check
        bool isValid() const;

        // Editor: state
        FollowedSkeletonInfo& state();

        // Editor: start editing
        void start_editing();

#ifndef YARP_NO_DEPRECATED // Since YARP 3.2
        YARP_DEPRECATED_MSG("Use start_editing() instead")
        void begin()
        {
            start_editing();
        }
#endif // YARP_NO_DEPRECATED

        // Editor: stop editing
        void stop_editing();

#ifndef YARP_NO_DEPRECATED // Since YARP 3.2
        YARP_DEPRECATED_MSG("Use stop_editing() instead")
        void end()
        {
            stop_editing();
        }
#endif // YARP_NO_DEPRECATED

        // Editor: tag field
        void set_tag(const std::string& tag);
        const std::string& get_tag() const;
        virtual bool will_set_tag();
        virtual bool did_set_tag();

        // Editor: x field
        void set_x(const double x);
        double get_x() const;
        virtual bool will_set_x();
        virtual bool did_set_x();

        // Editor: y field
        void set_y(const double y);
        double get_y() const;
        virtual bool will_set_y();
        virtual bool did_set_y();

        // Editor: z field
        void set_z(const double z);
        double get_z() const;
        virtual bool will_set_z();
        virtual bool did_set_z();

        // Editor: coronal field
        void set_coronal(const yarp::sig::Vector& coronal);
        const yarp::sig::Vector& get_coronal() const;
        virtual bool will_set_coronal();
        virtual bool did_set_coronal();

        // Editor: sagittal field
        void set_sagittal(const yarp::sig::Vector& sagittal);
        const yarp::sig::Vector& get_sagittal() const;
        virtual bool will_set_sagittal();
        virtual bool did_set_sagittal();

        // Editor: clean
        void clean();

        // Editor: read
        bool read(yarp::os::ConnectionReader& connection) override;

        // Editor: write
        bool write(yarp::os::ConnectionWriter& connection) const override;

    private:
        // Editor: state
        FollowedSkeletonInfo* obj;
        bool obj_owned;
        int group;

        // Editor: dirty variables
        bool is_dirty;
        bool is_dirty_tag;
        bool is_dirty_x;
        bool is_dirty_y;
        bool is_dirty_z;
        bool is_dirty_coronal;
        bool is_dirty_sagittal;
        int dirty_count;

        // Editor: send if possible
        void communicate();

        // Editor: mark dirty overall
        void mark_dirty();

        // Editor: mark dirty single fields
        void mark_dirty_tag();
        void mark_dirty_x();
        void mark_dirty_y();
        void mark_dirty_z();
        void mark_dirty_coronal();
        void mark_dirty_sagittal();

        // Editor: dirty_flags
        void dirty_flags(bool flag);
    };

private:
    // read/write tag field
    bool read_tag(yarp::os::idl::WireReader& reader);
    bool write_tag(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_tag(yarp::os::idl::WireReader& reader);
    bool nested_write_tag(const yarp::os::idl::WireWriter& writer) const;

    // read/write x field
    bool read_x(yarp::os::idl::WireReader& reader);
    bool write_x(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_x(yarp::os::idl::WireReader& reader);
    bool nested_write_x(const yarp::os::idl::WireWriter& writer) const;

    // read/write y field
    bool read_y(yarp::os::idl::WireReader& reader);
    bool write_y(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_y(yarp::os::idl::WireReader& reader);
    bool nested_write_y(const yarp::os::idl::WireWriter& writer) const;

    // read/write z field
    bool read_z(yarp::os::idl::WireReader& reader);
    bool write_z(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_z(yarp::os::idl::WireReader& reader);
    bool nested_write_z(const yarp::os::idl::WireWriter& writer) const;

    // read/write coronal field
    bool read_coronal(yarp::os::idl::WireReader& reader);
    bool write_coronal(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_coronal(yarp::os::idl::WireReader& reader);
    bool nested_write_coronal(const yarp::os::idl::WireWriter& writer) const;

    // read/write sagittal field
    bool read_sagittal(yarp::os::idl::WireReader& reader);
    bool write_sagittal(const yarp::os::idl::WireWriter& writer) const;
    bool nested_read_sagittal(yarp::os::idl::WireReader& reader);
    bool nested_write_sagittal(const yarp::os::idl::WireWriter& writer) const;
};

#endif // YARP_THRIFT_GENERATOR_STRUCT_FOLLOWEDSKELETONINFO_H
