/*
 * Copyright (C) 2006-2019 Istituto Italiano di Tecnologia (IIT)
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms of the
 * BSD-3-Clause license. See the accompanying LICENSE file for details.
 */

// Autogenerated by Thrift Compiler (0.12.0-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_HUMANSTRUCTURE_IDLSERVER_H
#define YARP_THRIFT_GENERATOR_SERVICE_HUMANSTRUCTURE_IDLSERVER_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

/**
 * humanStructure_IDLServer
 * IDL Interface to \ref human structure module.
 */
class humanStructure_IDLServer :
        public yarp::os::Wire
{
public:
    // Constructor
    humanStructure_IDLServer();

    /**
     * Set the threshold number for finding the arm.
     * @return true/false on success/failure
     */
    virtual bool setArmThresh(const std::int32_t threshold);

    /**
     * Get threshold value for finding the arm.
     * @return number of frames
     */
    virtual std::int32_t getArmThresh();

    /**
     * Quit the module.
     * @return true/false on success/failure.
     */
    virtual bool quit();

    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_HUMANSTRUCTURE_IDLSERVER_H
