/*
 * Copyright (C) 2006-2019 Istituto Italiano di Tecnologia (IIT)
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms of the
 * BSD-3-Clause license. See the accompanying LICENSE file for details.
 */

// Autogenerated by Thrift Compiler (0.12.0-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_LINEDETECTOR_IDL_H
#define YARP_THRIFT_GENERATOR_SERVICE_LINEDETECTOR_IDL_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <yarp/os/Property.h>

/**
 * lineDetector_IDL
 * IDL Interface to lineDetector services.
 */
class lineDetector_IDL :
        public yarp::os::Wire
{
public:
    // Constructor
    lineDetector_IDL();

    /**
     * Start detection of start/finish line.
     * @param line string indicating the line to detect, start-line or finish-line.
     * @param timeout optional timeout in seconds, if > 0.
     * @return true on success/failure.
     */
    virtual bool detect(const std::string& line, const std::int32_t timeout = 0);

    /**
     * Retrieve line.
     * @param line string indicating the line to detect, start-line or finish-line.
     * @return a property-like object in the form
     *         (pose_world (x y z ax ay az theta))
     *         (line_size (lenght width)).
     */
    virtual yarp::os::Property get_line(const std::string& line);

    /**
     * Delete lines from opc and skeletonViewer.
     * @return true/false on success/failure.
     */
    virtual bool reset();

    /**
     * Update robot's odometry with respect to specified line.
     * @param line_tag string indicating line with respect to calibrate, start-line or finish-line.
     * @param theta angle-coordinate to reach the specified line (degrees).
     * @return true/false on success/failure.
     */
    virtual bool update_odometry(const std::string& line_tag, const double theta);

    /**
     * Navigate to the specified line.
     * @param line_tag string indicating line with respect to calibrate, start-line or finish-line.
     * @param theta angle-coordinate to reach the specified line (degrees).
     * @return true/false on success/failure.
     */
    virtual bool go_to_line(const std::string& line_tag, const double theta);

    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_LINEDETECTOR_IDL_H
