/*
 * Copyright (C) 2006-2020 Istituto Italiano di Tecnologia (IIT)
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms of the
 * BSD-3-Clause license. See the accompanying LICENSE file for details.
 */

// Autogenerated by Thrift Compiler (0.12.0-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_MANAGERTUG_IDL_H
#define YARP_THRIFT_GENERATOR_SERVICE_MANAGERTUG_IDL_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

/**
 * managerTUG_IDL
 * IDL Interface to Manager Tug services.
 */
class managerTUG_IDL :
        public yarp::os::Wire
{
public:
    // Constructor
    managerTUG_IDL();

    /**
     * Start the interaction.
     * @return true/false on success/failure.
     */
    virtual bool start();

    /**
     * Stop the interaction.
     * @return true/false on success/failure.
     */
    virtual bool stop();

    /**
     * Trigger speech.
     * @return true/false on success/failure.
     */
    virtual bool trigger();

    /**
     * Set target to reach in simulation. Valid only if simulation is set to true.
     * @param x x-coordinate of the target to reach.
     * @param y y-coordinate of the target to reach.
     * @param theta theta angle of the target to reach.
     * @return true/false on success/failure.
     */
    virtual bool set_target(const double x = 4.5, const double y = 0, const double theta = 0);

    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_MANAGERTUG_IDL_H
