/*
 * Copyright (C) 2006-2019 Istituto Italiano di Tecnologia (IIT)
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms of the
 * BSD-3-Clause license. See the accompanying LICENSE file for details.
 */

// Autogenerated by Thrift Compiler (0.12.0-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_ROBOTSKELETONPUBLISHER_IDL_H
#define YARP_THRIFT_GENERATOR_SERVICE_ROBOTSKELETONPUBLISHER_IDL_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>

/**
 * robotSkeletonPublisher_IDL
 * IDL Interface to Skeleton Player services.
 */
class robotSkeletonPublisher_IDL :
        public yarp::os::Wire
{
public:
    // Constructor
    robotSkeletonPublisher_IDL();

    /**
     * Set visibility in the viewer.
     * @param flag true/false to set/unset visibility.
     * @return true/false on success/failure.
     */
    virtual bool set_visibility(const bool flag);

    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_ROBOTSKELETONPUBLISHER_IDL_H
