version: "3.7"

x-fdg-basic: &fdg-basic
  image: ghcr.io/robotology/assistive-rehab:master-basic
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
    - YARP_DATA_DIRS=${YARP_DATA_DIRS}:/projects/yarp-devices-ros2/build/share/yarp/:/usr/local/lib/yarp:/projects/yarp-devices-ros2/build/share/yarp/:/projects/yarp-devices-ros2/build/share/yarp-devices-ros2
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/.config/yarp:/root/.config/yarp"
    - "${ROBOT_CODE}/assistive-rehab:/projects/assistive-rehab"
    - "${HOME}/etapas-results/motion-analysis:/root/.local/share/yarp/contexts/motionAnalyzer" #for saving the results from motionAnalyzer
    - "${HOME}/etapas-results/events:/root/.local/share/yarp/contexts/eventCollector" #for saving the results from eventCollector
  network_mode: "host"
  privileged: true

x-fdg-openpose: &fdg-openpose
  image: elandini84/r1images:r1OpenPose_fdg
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/.config/yarp:/root/.config/yarp"
    - "${ROBOT_CODE}/assistive-rehab:/projects/assistive-rehab"
  network_mode: "host"
  privileged: true

x-fdg-speech: &fdg-speech
  image: ghcr.io/robotology/assistive-rehab:master-speech
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
    - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    - FILE_INPUT=google-key.json
    - XDG_RUNTIME_DIR
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/.config/yarp:/root/.config/yarp"
    - "${ROBOT_CODE}/assistive-rehab:/projects/assistive-rehab"
    - "${ROBOT_CODE}/assistive-rehab-private/google:/root/authorization"
    - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
    - "~/.config/pulse/cookie:/root/.config/pulse/cookie"
  network_mode: "host"
  privileged: true

# docker run --rm -it --network host --device /dev/snd -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native -v ~/.config/pulse/cookie:/root/.config/pulse/cookie --group-add $(getent group audio | cut -d: -f3) --privileged --env FILE_INPUT=google-key.json --mount type=bind,source=${HOME}/teamcode/key,target=/root/authorization --mount type=bind,source=${HOME}/.config/yarp,target=/root/.config/yarp ghcr.io/robotology/assistive-rehab:v2022.05.2-speech bash

services:
  yarprunSpeech:
    <<: *fdg-speech
    command: sh -c "yarp run --server /container-speech --log"

  yarprunConsole:
    <<: *fdg-basic
    command: sh -c "yarprun --server /container-console --log"

  yarprunOpenpose:
    <<: *fdg-openpose
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: sh -c "yarprun --server /container-openpose"


