version: "3.7"

x-fdg-basic: &fdg-basic
  image: ghcr.io/robotology/assistive-rehab:master-basic-devel
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
    - YARP_DATA_DIRS=${YARP_DATA_DIRS}:/projects/yarp-devices-ros2/build/share/yarp/
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/.config/yarp:/root/.config/yarp"
    - "${HOME}/etapas-results/motion-analysis:/root/.local/share/yarp/contexts/motionAnalyzer" #for saving the results from motionAnalyzer
    - "${HOME}/etapas-results/events:/root/.local/share/yarp/contexts/eventCollector" #for saving the results from eventCollector
  network_mode: "host"
  privileged: true

services:
  yarprunConsole:
    <<: *fdg-basic
    command: sh -c "yarprun --server /r1-console --log"

  objectsPropertiesCollector:
    <<: *fdg-basic
    command: sh -c "objectsPropertiesCollector --name opc --no-load-db --no-save-db --sync-bc 0.1"

  skeletonViewer:
    <<: *fdg-basic
    command: sh -c "skeletonViewer --x 1120 --y 10 --show-floor on --camera-viewup '(1.0 0.0 0.0)' --camera-position '(-4.0 -2.0 8.0)' --camera-focalpoint '(0.0 -2.0 0.0)' --grid-resolution '(100 100)'"

  lineDetector:
    <<: *fdg-basic
    command: sh -c "yarp wait /depthCamera/rgbImage:o; lineDetector --camera::remote /depthCamera"

  skeletonRetriever:
    <<: *fdg-basic
    command:
      - /bin/bash
      - -c
      - |
        yarp wait /depthCamera/rgbImage:o
        yarp wait /depthCamera/depthImage:o
        yarp wait /opc/rpc
        skeletonRetriever --depth::enable true --depth::kernel-size 8  --depth::iterations 1 --depth::min-distance 0.6 --depth::max-distance 6.0 --filtering::filter-keypoint-order 12

  skeletonLocker:
    <<: *fdg-basic
    command: sh -c "skeletonLocker"

  robotSkeletonPublisher:
    <<: *fdg-basic
    command: sh -c "yarp wait /cer/head/command:i; yarp wait /cer/head/rpc:i; yarp wait /cer/head/state:o; yarp wait /cer/head/stateExt:o; yarp wait /cer/torso/command:i; yarp wait /cer/torso/rpc:i; yarp wait /cer/torso/state:o; yarp wait /cer/torso/stateExt:o; yarp wait /cer/torso_tripod/command:i; yarp wait /cer/torso_tripod/rpc:i; yarp wait /cer/torso_tripod/state:o; yarp wait /cer/torso_tripod/stateExt:o; yarp wait /cer/left_arm/command:i; yarp wait /cer/left_arm/rpc:i; yarp wait /cer/left_arm/state:o; yarp wait /cer/left_arm/stateExt:o; yarp wait /cer/right_arm/command:i; yarp wait /cer/right_arm/rpc:i; yarp wait /cer/right_arm/state:o; yarp wait /cer/right_arm/stateExt:o; yarp wait /cer/left_wrist_tripod/command:i; yarp wait /cer/left_wrist_tripod/rpc:i; yarp wait /cer/left_wrist_tripod/state:o; yarp wait /cer/left_wrist_tripod/stateExt:o; yarp wait /cer/right_wrist_tripod/command:i; yarp wait /cer/right_wrist_tripod/rpc:i; yarp wait /cer/right_wrist_tripod/state:o; yarp wait /cer/right_wrist_tripod/stateExt:o; robotSkeletonPublisher --robot cer"

  attentionManager:
    <<: *fdg-basic
    command: sh -c "attentionManager --frame world"

  motionAnalyzer:
    <<: *fdg-basic
    command: sh -c "motionAnalyzer"

  managerTUG:
    <<: *fdg-basic
    restart: on-failure
    command:
      - /bin/bash
      - -c
      - |
        yarp wait /attentionManager/cmd:rpc
        yarp wait /motionAnalyzer/cmd
        yarp wait /iSpeak
        yarp wait /iSpeak/rpc
        yarp wait /navController/rpc
        yarp wait /skeletonLocker/rpc
        yarp wait /googleSpeechProcess/result:o
        yarp wait /opc/broadcast:o
        yarp wait /ctpservice/left_arm/rpc
        yarp wait /ctpservice/right_arm/rpc
        yarp wait /obstacleDetector/obstacle:o
        managerTUG --lock false --max-timeout 30.0 --engage-azimuth "(50.0 160.0)" --starting-pose "(2 -4.0 110.0)"

  gazeController:
    <<: *fdg-basic
    restart: on-failure
    command: sh -c "yarp wait /cer/head/command:i; yarp wait /cer/head/rpc:i; yarp wait /cer/head/state:o; cer_gaze-controller --cameras::file /projects/cer/build/share/CER/contexts/cameraCalibration/cerEyes_640x480.ini"

  navController:
    <<: *fdg-basic
    command: sh -c "yarp wait /baseControl/rpc; yarp wait /odometry2D_nws_yarp/odometry:o; yarp wait /baseControl/input/command:i; navController --velocity-linear-magnitude 0.6 --velocity-angular-saturation 15.0 --distance-target 1.8"

  obstacleDetector:
    <<: *fdg-basic
    command: sh -c "yarp wait /navController/rpc; obstacleDetector --robot cer --dist-obstacle 0.6"

  ctpServiceRight:
    <<: *fdg-basic
    command: sh -c "yarp wait /cer/right_arm/command:i; yarp wait /cer/right_arm/rpc:i; yarp wait /cer/right_arm/state:o; yarp wait /cer/right_arm/stateExt:o; ctpService --robot cer --part right_arm"

  ctpServiceLeft:
    <<: *fdg-basic
    command: sh -c "yarp wait /cer/left_arm/command:i; yarp wait /cer/left_arm/rpc:i; yarp wait /cer/left_arm/state:o; yarp wait /cer/left_arm/stateExt:o; ctpService --robot cer --part left_arm"

  eventCollector:
    <<: *fdg-basic
    command: sh -c "eventCollector"
