version: "3.7"
x-fdg-speech: &fdg-speech
  image: ghcr.io/robotology/assistive-rehab:master-speech-fake
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
    - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    - FILE_INPUT=google-key.json
    - ROBOT_CODE=/projects
    - XDG_RUNTIME_DIR
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/.config/yarp:/root/.config/yarp"
    - "${ROBOT_CODE}/assistive-rehab-private/google:/root/authorization"
    - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
    - "~/.config/pulse/cookie:/root/.config/pulse/cookie"
  network_mode: "host"
  privileged: true

# docker run --rm -it --network host --device /dev/snd -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native -v ~/.config/pulse/cookie:/root/.config/pulse/cookie --group-add $(getent group audio | cut -d: -f3) --privileged --env FILE_INPUT=google-key.json --mount type=bind,source=${HOME}/teamcode/key,target=/root/authorization --mount type=bind,source=${HOME}/.config/yarp,target=/root/.config/yarp ghcr.io/robotology/assistive-rehab:v2022.05.2-speech-fake bash

services:
  node-button.js:
    <<: *fdg-speech
    command: sh -c "cd /projects/assistive-rehab/app/scripts; /root/.nvm/versions/node/v14.17.0/bin/node node-button.js --host 0.0.0.0 --listenPort 80"
  
  # microphone:
  #   <<: *fdg-speech
  #   command: sh -c "yarpdev --device AudioRecorderWrapper --subdevice portaudioRecorder --name /microphone --min_samples_over_network 4000 --max_samples_over_network 4000 --AUDIO_BASE::channels 1 --AUDIO_BASE::samples 16000 --AUDIO_BASE::rate 16000"

  fakeGoogleSpeech:
    <<: *fdg-speech
    command: sh -c "fakeGoogleSpeech --language_code it-IT"
  
  fakeGoogleSpeechProcess:
    <<: *fdg-speech
    command: sh -c "fakeGoogleSpeechProcess"
